#!/bin/bash


# make a folder for uploading the images to later
mkdir SLIDESHOW_IMGS


# I DON'T THINK ANY OF THIS BELOW IS NOW NECESSARY AS EXTENSIONS WORK BETTER IN JupyterLAb 3 and table of contents is built-in
# COMMENT OUT ALL BELOW THIS FOR NOW.
#-----------------------------------------------------------------------
# Add in ipywidgets extension so Halo works in notebook
# Adding and enabling ipywidgets based on https://github.com/binder-examples/jupyter-extension/commit/63bd1a323a4bacead2afbfb3522f8053ffc39250
# with an update to the jupyterlab install step, see https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension,
#  since I am using JupyterLab latest which at present is 1.2.6, and not 0.38 which the binder example uses
# Realized Halo needs ipywidgets from 
# https://github.com/manrajgrover/halo/pull/40 &
# https://github.com/manrajgrover/halo/issues/32#issuecomment-354426261.
#jupyter contrib nbextension install --user
#jupyter nbextension enable --py widgetsnbextension
#jupyter labextension install @jupyter-widgets/jupyterlab-manager
#jupyter labextension install @jupyterlab/toc

# Upon addition of Jupytext, I was seeing it want to build when session launched. Seems
# explained at https://jupytext.readthedocs.io/en/latest/install.html#jupytext-commands-in-jupyterlab
# >"The Jupytext extension for JupyterLab is bundled with Jupytext. Installing Jupytext will trigger a build of JupyterLab the next time you open it. If you prefer, you can trigger the build manually with `jupyter lab build`"
# Trying that here to avoid it later showing pop-up about it.
#jupyter lab build
