#!/bin/bash

# clean up a bit since will be using the starting directory to work
rm requirements.txt
rm postBuild
rm apt.txt
rm README.md
rm LICENSE
rm RISEnb_stub.ipynb



# this must be last line according to 
# https://repo2docker.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"